#!/usr/bin/python
# -*- coding: utf-8 -*-

# mkdir /var/tmp/pisi/cache
# ./fetch_file file:///etc/passwd
# ./fetch http://cekirdek.uludag.org.tr/~meren/Imagi.mp3 
# ./fetch_file ftp://ftp.uludag.org.tr/pub/md5summer.exe
# ls /var/tmp/pisi/cache

import sys
from sys import stderr
sys.path.append("..")
from pisi import fetcher
import pisi.config

def doProgress(pd):
    out = '\r%-30.30s %3d%% %12.2f %s' % \
        (pd['filename'], pd['percent'], pd['rate'], pd['symbol'])
    stderr.write(out)
    stderr.flush()

if len(sys.argv) == 2:
    obj = fetcher.Fetcher(sys.argv[1])
    obj.percentHook = doProgress
    saved_file = obj.fetch()
    if saved_file:
        print "File saved: %s" % (saved_file)
else:
    print """
    fetcher.py için test uygulaması.. Parametre olarak verilen URI'deki dosyayı '%s' hedefine kaydeder..

    Örnek:

    ./fetch_file file:///etc/passwd
    ./fetch_file http://cekirdek.uludag.org.tr/~meren/Imagi.mp3 
    ./fetch_file ftp://ftp.uludag.org.tr/pub/md5summer.exe

    """ % (pisi.config.archives_dir)

