#!/usr/bin/python
# -*- coding: utf-8 -*-
# ./getTextForNode ../../popt/popt.pspec PSPEC/Source/Name

import sys
sys.path.append("..")
import specfile

s = specfile.SpecFile(sys.argv[1])

text = s.getFirstChildText(sys.argv[2])
print text

