#!/usr/bin/python
# -*- coding: utf-8 -*-
# ./getTextForNode ../../popt/popt.pspec PSPEC/Source/Name

import sys
sys.path.append("..")
from pisi import specfile

s = specfile.SpecFile()
s.read(sys.argv[1])

print "PSPEC/Source/Name", s.sourceName

print "* patches"
for patch in s.patches:
    print "\tpatch fn:", patch.filename
    print "\tpatch ct:", patch.compressionType

print "* buildDeps"
for dep in s.buildDeps:
    print "\tdep nm:", dep.package
    print "\tdep vf:", dep.versionFrom

print "* packages"
for package in s.packages:
    print "\tPackage", package.name


