#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import zipfile

if not sys.argv[1]:
    print "pisi file name required..."
    sys.exit()

if not zipfile.is_zipfile(sys.argv[1]):
    print "ZIP file required..."
    sys.exit()

f = zipfile.ZipFile(sys.argv[1], "r")

for file in f.namelist():
    print file
