#!/usr/bin/python
#
# Copyright (C) 2005, TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.
#

from pisi.cli.pisicli import PisiCLI

if __name__ == "__main__":
    try:
        cli = PisiCLI()
        cli.runCommand()
    except KeyboardInterrupt:
        import sys
        from pisi.ui import ui

        ui.error("\nKeyboardIntterupt: exiting...\n")
        sys.exit(1)
        
