#!/usr/bin/python
# -*- coding: utf-8 -*-

# python standard library
from os.path import basename
import sys
from optparse import OptionParser

# pisi modules
sys.path.append("./lib")
import pisi.context
import pisi.util
from pisi.build import PisiBuild, PisiBuildError

def main():

    # common options

    usage = "usage: %prog [options] package-name.pspec"
    import pisi.cli.commonargs
    parser = OptionParser(usage=usage,version="%prog " + pisi.__version__)
    parser = pisi.cli.commonargs.add(parser)

    (options, args) = parser.parse_args()

    # pspec(PISI Spec) to be used for package
    for pspec in args:
        # What we need to do first is create a context with our specfile
        ctx = pisi.context.BuildContext(pspec)
        # don't do the real job here. this is just a CLI!
        pb = PisiBuild(ctx)
        pb.build()

if __name__ == "__main__":
    main()
