#!/bin/bash
#define constants
available_build_types=(autotools cmaketools mesontools qt)
inf_msg(){
    echo "Create new inary package template. "
}

err_msg(){
      echo "Usage: $(basename $0) -n package-name -a source-url [OPTIONS]" >&2
      echo "  General Options:"
      echo "    -o   output directory (default: package name)"
      echo "    -n   package name (required)"
      echo "    -x   build package after create [true/false] (default false)"
      echo "    -h   write help message"
      echo "  Actions options:"
      echo "    -t   build type (default: autotools)"
      echo "           Build types: ${available_build_types[@]}"
      echo "    -c   configure options"
      echo "  Pspec options:"
      echo "    Source section:"
      echo "      -p   homepage url"
      echo "      -u   packager name"
      echo "      -e   packager email adress"
      echo "      -l   package license"
      echo "      -i   isa value list"
      echo "      -s   package summary"
      echo "      -d   package description"
      echo "      -b   build dependencies list"
      echo "      -a   package source archive list (required)"
      echo "      -q   rfp status [true/false] (default true)"
      echo "    Package section:"
      echo "      -r   runtime dependencies list"
      echo "      -v   package verison"
      exit 1
}

#default variables
name=""
homepage="https://gitlab.com/sulinos/devel/inary"
buildtype="autotools"
packager="Your Name"
email="yourmane@example.org"
license="GPLv3"
isa=""
summary="Package summary missing"
description="Package description missing"
src=""
bdeps=""
rdeps=""
ver="1.0.0"
rfp=true
bnow=false
confopt=""
#opt parse
while getopts -- ':o:n:x:t:c:p:u:e:l:i:s:d:b:a:r:v:q:' OPTION; do
  case "$OPTION" in
   o)
      directory="${OPTARG[@]}"
      ;;

   n)
      name="${OPTARG[@]}"
      ;;
   x)
     bnow="${OPTARG[@]}"
     if [ "$bnow" != "true" ] && [ "$bnow" != "false" ]; then
        echo "Error: Invalid status: $bnow"
        err_msg
      fi
     ;;
   t)
      buildtype="${OPTARG[@]}"
      a=0
      for item in ${available_build_types[@]}
      do
        if [ "$buildtype" == "$item" ]; then
          a=1
        fi
      done
      if [ "$a" == "0" ] ; then
        echo "Error: Invalid build type: $a $buildtype"
        err_msg
      fi
      ;;
      
    c)
      confopt="${OPTARG[@]}"
      ;;
    p)
      homepage="${OPTARG[@]}"
      ;;
      
    u)
      packager="${OPTARG[@]}"
      ;;
      
    e)
      email="${OPTARG[@]}"
      ;;
      
    l)
      license="${OPTARG[@]}"
      ;;
      
    i)
      isa="${OPTARG[@]}"
      ;;
      
    s)
      summary="${OPTARG[@]}"
      ;;
      
    d)
      description="${OPTARG[@]}"
      ;;      
      
    b)
      bdeps="${OPTARG[@]}"
      ;;
      
    a)
      src="${OPTARG[@]}"
      ;;
      
    r)
      rdeps="${OPTARG[@]}"
      ;;
      
    v)
      ver="${OPTARG[@]}"
      ;;
    q)
      rfp="${OPTARG[@]}"
      if [ "$rfp" != "true" ] && [ "$rfp" != "false" ]; then
        echo "Error: Invalid rfp status: $rfp"
        err_msg
      fi
      ;;
    ?)
      inf_msg
      err_msg
      ;;
  esac
done

#check options
if [ "$name" == "" ] ; then
    echo "Error: package name missing."
    err_msg
fi
if [ "$directory" == "" ] ; then
    directory=$name
fi
if [ "$src" == "" ] ; then
    echo "Error: source archive missing."
    err_msg
fi

write_pspec(){
echo "<?xml version=\"1.0\" ?>"
echo "<!DOCTYPE INARY SYSTEM \"https://gitlab.com/sulinos/sulinproject/inary/raw/master/inary-spec.dtd\">"
echo "<INARY>"
echo "    <Source>"
echo "        <Name>$name</Name>"
if [ "$rfp" != "false" ] ; then
  echo "        <Rfp>$name is a rfp package</Rfp>"
fi
echo "        <Homepage>$homepage</Homepage>"
echo "        <Packager>"
echo "            <Name>$packager</Name>"
echo "            <Email>$email</Email>"
echo "        </Packager>"
echo "        <License>$license</License>"
for i in $isa ; do
  echo "        <IsA>$i/IsA>"
done
echo "        <Summary>$summary</Summary>"
echo "        <Description>$description</Description>"
for i in $src ; do
  out=$(mktemp)
  wget -c $i -O $out
  echo "        <Archive sha1sum=\"$(sha1sum $out | sed 's/ .*//g')\">$i</Archive>"
  rm -f $out
done
echo "        <BuildDependencies>"
for i in $bdeps ; do
  echo "            <Dependency>$i</Dependency>"
done
echo "        </BuildDependencies>"
echo "    </Source>"

echo "    <Package>"
echo "        <Name>$name</Name>"
echo "        <RuntimeDependencies>"
for i in $rdeps ; do
  echo "            <Dependency>$i</Dependency>"
done
echo "        </RuntimeDependencies>"
cat << EOF
        <Files>
            <Path fileType="config">/etc</Path>
            <Path fileType="localedata">/usr/share/locale</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="man">/usr/share/man</Path>
            <Path fileType="info">/usr/share/info</Path>
            <Path fileType="data">/usr/share</Path>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="library">/lib</Path>
            <Path fileType="library">/usr/libexec</Path>
            <Path fileType="executable">/bin</Path>
        </Files>
    </Package>
EOF
echo "    <Package>"
echo "        <Name>$name-32bit</Name>"
echo "        <RuntimeDependencies>"
for i in $rdeps ; do
  echo "            <Dependency>$i-32bit</Dependency>"
done
echo "        </RuntimeDependencies>"
cat << EOF
        <Files>
            <Path fileType="library">/usr/lib32</Path>
            <Path fileType="library">/lib32</Path>
        </Files>
    </Package>
EOF
echo "    <Package>"
echo "        <Name>$name-devel</Name>"
echo "        <RuntimeDependencies>"
for i in $rdeps ; do
  echo "            <Dependency>$i-devel</Dependency>"
done
echo "        </RuntimeDependencies>"
cat << EOF
        <Files>
            <Path fileType="data">/usr/lib/pkgconfig</Path>
            <Path fileType="header">/usr/include</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
EOF
echo "            <Date>$(date "+%Y-%m-%d")</Date>"
echo "            <Version>$ver</Version>"
echo "            <Comment>First release</Comment>"
echo "            <Name>$packager</Name>"
echo "            <Email>$email</Email>"
echo "        </Update>"
echo "    </History>"
echo "</INARY>"


}
write_actions(){
cat << EOF
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Licensed under the GNU General Public License, version 3.
# See the file http://www.gnu.org/licenses/gpl.txt
from inary.actionsapi import inarytools
EOF
echo "from inary.actionsapi import $buildtype as tools"
cat << EOF
from inary.actionsapi import get
#more information : https://gitlab.com/sulinos/inary/tree/master/inary/actionsapi
def setup():
EOF
echo "    tools.configure(\"$confopt\")"
cat << EOF
def build():
    tools.make()

def install():
    tools.rawInstall("DESTDIR=%s" % get.installDIR())

EOF
}
mkdir -p $(pwd)/$name
echo "Creating pspec.xml to $(pwd)/$name/pspec.xml"
write_pspec > $(pwd)/$name/pspec.xml
echo "Creating actions.py to $(pwd)/$name/actions.py"
write_actions > $(pwd)/$name/actions.py

if [ "$bnow" == "true" ] ; then
  cd $(pwd)/$name
  inary bi --verbose --debug
fi
