#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2005, TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.

import sys
import pisi

def show_info(filename):
    pisi.api.init(database=False)
    metadata, files = pisi.api.info_file(filename)
    paths = [fileinfo.path for fileinfo in files.list]
    paths.sort()
    for path in paths:
        print '/' + path
    pisi.api.finalize()
    return 0

if __name__ == "__main__":
    for x in sys.argv[1:]:
        show_info(x)
