#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2006-2010, TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.

import os
import sys
from zipfile import BadZipfile

import pisi
from pisi.archive import ArchiveZip, ArchiveTar
import pisi.context as ctx
import pisi.util as util

def usage(errmsg):
    print """
    Error: %s

    Usage:
      unpisi PiSi_package.pisi
    """ % (errmsg)

    sys.exit(1)

def main():

    if len(sys.argv) < 2:
        usage("PiSi package required..")

    elif not os.path.exists(sys.argv[1]):
        usage("File %s not found" % sys.argv[1])

    try:
        arc = ArchiveZip(sys.argv[1], 'zip', 'r')
    except BadZipfile, e:
        print e
        sys.exit(1)

    arc.unpack_files(['files.xml', 'metadata.xml'], '.')
    arc.unpack_dir('comar', '.')

    archive_name = None
    if arc.has_file(ctx.const.install_tar_xz):
        archive_name = ctx.const.install_tar_xz
        archive_format = "tarxz"
    elif arc.has_file(ctx.const.install_tar_lzma):
        archive_name = ctx.const.install_tar_lzma
        archive_format = "tarlzma"

    if archive_name:
        tar_file = arc.open(archive_name)
        tar = ArchiveTar(fileobj=tar_file, arch_type=archive_format)
        tar.unpack_dir('.')

    return 0

if __name__ == "__main__":
    sys.exit(main())
