#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2006, TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.

# a Simple helper script for PiSi to set default repo

import os
import sys

import pisi
import pisi.context as ctx

def usage():
    print """
    Usage:
      pisisdr reponame
    """
    sys.exit(1)

def main():
    if len(sys.argv) < 2:
        usage()

    repo = sys.argv[1]

    try:    
        ctx.repodb.set_default_repo(repo)
    except pisi.lockeddbshelve.Error, e:
        print e

if __name__ == "__main__":
    sys.exit(main())
