#! /usr/bin/python
# -*- python -*-

#import package
#import parsespec
#import repodb
#import packagedb
#import dependency
#import conflicts


# extract control files

# verify package

# check file semantics
# check file system requirements
# check conflicts
# check dependencies

# unzip package in place

# update databases

# packagedb

