#!/usr/bin/python
# -*- coding: utf-8 -*-

from gnuconfig import *
from libtoolize import *
from autotools import *

def src_setup():
	gnuconfig_update()
	libtoolize()
	configure( '--with-nls' )

def src_build():
	make()

def src_install():
	install()
