#!/usr/bin/python
# -*- coding: utf-8 -*-

from gnuconfig import *
from libtoolize import *
from autotools import *

import pisiconfig

package_name = 'popt-1.7'

def setup:
	gnuconfig_update( package_name )
	libtoolize()
	configure( '--with-nls' )
def build:
	make()

def install:
	install()
